### ISSUE TITLE
model training error

### ISSUE THREAD

**Issue by XiongGZ** [HUST-NingKang-Lab/EXPERT#10]
It reports an error when I try to ab init train model, I can't understand.

Could you help me solve this problem? Thanks!
![QQ图片20211214135935](https://user-images.githubusercontent.com/63765061/145941981-bc584738-714d-4607-aa64-7f0ef96cbc2c.png)

**Comment by AdeBC** [comment]
Thanks for reaching out!

Seems this is an issue related to the TensorFlow package, please try re-install `tensorflow 2.4`. 

We developed EXPERT based on this version, later versions may include some API changes and produce this error.

**Comment by XiongGZ** [comment]
> Thanks for reaching out!
> 
> Seems this is an issue related to the TensorFlow package, please try re-install `tensorflow 2.4`.
> 
> We developed EXPERT based on this version, later versions may include some API changes and produce this error.

OK, it worked, thanks!
