### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by wangnan990826** [HUST-NingKang-Lab/EXPERT#9]
I install anaconda on the server, create and acitvate a virtual environment, but I can't find where is the download files of expert in the environment, what's wrong with my installation pipeline?

**Comment by AdeBC** [comment]
Thanks for reaching out. I suppose you've already installed EXPERT using `pip`, right? 

If so, you can find your installation files of EXPERT by `pip show expert-mst`. If you cannot execute `expert` command, then I guess you have to add installed pip packages to your system PATH. See [here](https://stackoverflow.com/questions/36092388/adding-installed-pip-package-to-path-automatically).

**Comment by wangnan990826** [comment]
Thanks for your replying, I have sovled the problem now.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月14日(星期二) 下午2:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HUST-NingKang-Lab/EXPERT] Installation error (Issue #9)





 
Thanks for reaching out. I suppose you've already installed EXPERT using pip, right?
 
If so, you can find your installation files of EXPERT by pip show expert-mst. If you cannot execute expert command, then I guess you have to add installed pip packages to your system PATH. See here.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AdeBC** [comment]
OKay! Good luck.
